### ISSUE TITLE
Extension is not loaded.

### ISSUE THREAD

**Issue by NikGovorov** [nuts4dotnet/TFSChatExtensions#2]
Hi,

I installed the extension and enabled popup notifications on Settings page but don't see any, in dev tools there are no any indications of errors/warnings/messages.

Is any way to get diagnostic information from the extension? I'm really keen on help get it working with on-premise TFS.

Thanks.

**Comment by jcoutch** [comment]
Hi @NikGovorov,

First, verify the chat extensions are loaded.  When you navigate to a team room, do you see "TFS Notification code has loaded" in the dev tools console?

If you do, look for an "Enable Desktop Notifications" button at the top right of the browser window.  If it's there, click on it, and grant the site permission to display desktop notifications.

If you don't see the button, or the button doesn't allow notifications to show up, navigate to chrome://settings/contentExceptions#notifications and verify your TFS site is allowed to show desktop notifications.  If it is, then we're onto debugging why it's not showing up.

Open up chrome://extensions/ and scroll down to TFS Chat Extensions, there's an ID.  If you open up the dev tools, switch to the "Sources" tab, and look in the list, you'll see the same ID.  If you expand that list and the subfolder, you'll see "TeamRoomScript.js"  You can set breakpoints within the script (I recommend the "parseMessage" and "show" methods) and send messages to test it.  Note - notifications won't appear for messages you send unless you enable it in the options (under chrome://extensions , click the "options" link under TFS Chat Extensions.  You will have to refresh your TFS chat window after any changes.)

If you don't see the "TFS Notification code has loaded" message in the dev tools console, that means it's not detecting that the room is a TFS team room.  The background script that handles it is hidden from dev tools (since it runs in the browser context and not the web context.)  If you want to debug that portion, you can pull this github repo, go to chrome://extensions/ and remove the extension currently installed.  Then, click "Developer Mode", and "Load Unpacked Extension".  Once you select the folder where the extension is, when you navigate to the page, you can then set breakpoints in background.js to see what's going on.

Hopefully that's enough to get you started on debugging this.  Let me know if you run into any issues or have questions.

Joe

**Comment by NikGovorov** [comment]
Hi @jcoutch,

Thanks for the detailed response.

> First, verify the chat extensions are loaded. When you navigate to a team room, do you see "TFS Notification code has loaded" in the dev tools console?

No, I don't.

> If you don't see the "TFS Notification code has loaded" message in the dev tools console, that means it's not detecting that the room is a TFS team room. The background script that handles it is hidden from dev tools (since it runs in the browser context and not the web context.) If you want to debug that portion, you can pull this github repo, go to chrome://extensions/ and remove the extension currently installed. Then, click "Developer Mode", and "Load Unpacked Extension". Once you select the folder where the extension is, when you navigate to the page, you can then set breakpoints in background.js to see what's going on.

![skitch](https://cloud.githubusercontent.com/assets/129254/11384432/7b6b1b0a-935b-11e5-9890-3ae25c09c0bf.png)

I don't see `background.js` script file in dev tools. I tried to add `debugger;` to `background.js` and reload the extension but it didn't start debugger.

![skitch](https://cloud.githubusercontent.com/assets/129254/11384523/34ad20fe-935c-11e5-811e-76e667ec52ad.png)

![skitch](https://cloud.githubusercontent.com/assets/129254/11384550/6af7206a-935c-11e5-9d49-6da7f27d6cc4.png)

**Comment by NikGovorov** [comment]
When click on:

![skitch](https://cloud.githubusercontent.com/assets/129254/11384656/54554714-935d-11e5-8b18-647cf975bda9.png)

I see:

![skitch](https://cloud.githubusercontent.com/assets/129254/11384671/706e7664-935d-11e5-8d48-adfa84f73997.png)

_generated_background_page.html:

``` html
<!DOCTYPE html>
<body>
<script src="/src/store.js"></script>
<script src="/src/main.js"></script>
```

**Comment by NikGovorov** [comment]
The issue was in https://github.com/nuts4dotnet/TFSChatExtensions/blob/master/manifest.json#L18,
my TFS installed on the following address: `http://tfs.contoso.com/tfs`. Created pull request https://github.com/nuts4dotnet/TFSChatExtensions/pull/3.

Thanks.
